# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '\u0423\u0441\u043b\u0443\u0433\u0430', 'verbose_name_plural': '\u0423\u0441\u043b\u0443\u0433\u0438'},
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(default='', help_text='\u043f\u0440\u0438\u043c\u0435\u0440: <i class="icon-our-service icon-house_sell"></i>', max_length=200, verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430 \u0434\u043b\u044f \u0443\u0441\u043b\u0443\u0433\u0438'),
            preserve_default=False,
        ),
    ]
