# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160307_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_home',
            field=models.BooleanField(default=False, verbose_name='\u0412\u044b\u0432\u043e\u0434 \u0432 \u0431\u043b\u043e\u043a 4 \u0443\u0441\u043b\u0443\u0433\u0438 \u043d\u0430 \u0433\u043b\u0430\u0432\u043d\u043e\u0439'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name="\u0412\u044b\u0432\u043e\u0434 \u0432 \u0431\u043b\u043e\u043a '\u041d\u043e\u0432\u0430\u044f \u0443\u0441\u043b\u0443\u0433\u0430'"),
        ),
    ]
