# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160307_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='photo',
            field=models.ImageField(null=True, upload_to='reviews', verbose_name='\u0424\u043e\u0442\u043e \u043a\u043b\u0438\u0435\u043d\u0442\u0430'),
        ),
    ]
