# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160307_2237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b'},
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='services'),
            preserve_default=False,
        ),
    ]
