# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20160309_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='services'),
            preserve_default=False,
        ),
    ]
