# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, max_length=80, verbose_name='\u041c\u0435\u0442\u0430 title'),
        ),
    ]
