# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:29
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20160503_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='preview_name',
            field=models.CharField(default='preview name for page', max_length=50, verbose_name='preview \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='preview_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='preview text for page'),
            preserve_default=False,
        ),
    ]
