# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 12:56
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20160519_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
