# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 12:00
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160521_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantages',
            name='long',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='\u0414\u043b\u0438\u043d\u043d\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='advantages',
            name='short',
            field=models.CharField(max_length=50, verbose_name='\u041a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
