# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:53
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0002_auto_20160307_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': '\u041f\u0440\u043e\u0435\u043a\u0442', 'verbose_name_plural': '\u041f\u0440\u043e\u0435\u043a\u0442\u044b'},
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='cropping_890x770',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='cropping_720x400',
            field=image_cropping.fields.ImageRatioField('image', '720x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 \u0434\u043b\u044f \u043a\u0430\u0442\u0440\u043e\u0447\u043a\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u0430'),
        ),
        migrations.AlterField(
            model_name='category',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
