# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0003_auto_20160307_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='badrooms',
            field=models.IntegerField(default=600, verbose_name='\u041a\u043e\u043b\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0441\u043f\u0430\u043b\u0435\u043d'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='bathrooms',
            field=models.IntegerField(default=2, verbose_name='\u041a\u043e\u043b\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0432\u0430\u043d\u043d\u044b\u0445 \u043a\u043e\u043c\u043d\u0430\u0442'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='square',
            field=models.IntegerField(default=2, verbose_name='\u041f\u043b\u043e\u0449\u0430\u0434\u044c \u0434\u043e\u043c\u0430'),
            preserve_default=False,
        ),
    ]
