# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0004_auto_20160307_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='for_sale',
            field=models.BooleanField(default=False, verbose_name='\u043d\u0430 \u043f\u0440\u043e\u0434\u0430\u0436\u0443'),
        ),
    ]
