# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 12:08
from __future__ import unicode_literals

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0007_auto_20160307_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='cropping_720x400',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='cropping_750x455',
            field=image_cropping.fields.ImageRatioField('image', '750x455', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 \u0434\u043b\u044f \u043a\u0430\u0442\u0440\u043e\u0447\u043a\u0438 \u043f\u0440\u043e\u0435\u043a\u0442\u0430 750x455'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '500x320', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 \u0434\u043b\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430 500x320'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='cropping_250x375',
            field=image_cropping.fields.ImageRatioField('image', '250x375', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 \u0434\u043b\u044f \u043f\u0440\u043e\u0435\u043a\u0442\u0430 250x375'),
        ),
    ]
