# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0010_auto_20160410_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='siteprojects.Amenities'),
        ),
    ]
