# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0011_auto_20160410_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin',
            field=models.CharField(default='Address \u2116123', max_length=100, verbose_name='\u0410\u0434\u0440\u0435\u0441'),
            preserve_default=False,
        ),
    ]
