# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0012_project_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='admin',
            new_name='address',
        ),
    ]
