# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteprojects', '0013_auto_20160410_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
