# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0014_project_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='\u0412 \u0438\u043d\u0442\u0435\u0440\u0435\u0441\u043d\u043e\u0435'),
        ),
    ]
