# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0005_auto_20160514_2133'),
        ('siteprojects', '0016_auto_20160503_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='filter',
            field=models.ManyToManyField(blank=True, to='ceilings.Filter'),
        ),
    ]
