# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20160503_1729'),
        ('siteprojects', '0016_auto_20160503_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='account',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Category'),
            preserve_default=False,
        ),
    ]
