# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 16:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteprojects', '0017_auto_20160514_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='address',
        ),
        migrations.RemoveField(
            model_name='project',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='project',
            name='badrooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.RemoveField(
            model_name='project',
            name='for_sale',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='project',
            name='square',
        ),
        migrations.RemoveField(
            model_name='project',
            name='text',
        ),
        migrations.DeleteModel(
            name='Amenities',
        ),
    ]
