# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 16:24
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_auto_20160503_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('slug', models.SlugField(help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0438.', unique=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0443')),
                ('icon', models.CharField(max_length=200, verbose_name='\u0418\u043a\u043e\u043d\u043a\u0430 \u0434\u043b\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('preview_name', models.CharField(max_length=50, verbose_name='preview \u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('preview_text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='\u041c\u0435\u0442\u0430 title')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('meta_description', models.CharField(blank=True, help_text='\u041d\u0443\u0436\u043d\u043e \u0434\u043b\u044f \u0421\u0415\u041e', max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u0430')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0430')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0442\u043e\u043b\u043e\u043a',
                'verbose_name_plural': '\u041f\u043e\u0442\u043e\u043b\u043a\u0438',
            },
        ),
    ]
