# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 14:04
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import image_cropping.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0026_auto_20160521_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceiling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0438.', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='\u041c\u0435\u0442\u0430 title')),
                ('meta_description', models.CharField(blank=True, help_text='\u041d\u0443\u0436\u043d\u043e \u0434\u043b\u044f \u0421\u0415\u041e', max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('preview_name', models.CharField(max_length=50, verbose_name='preview \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435(\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a)')),
                ('preview_text', models.TextField(verbose_name='preview \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\xb2')),
                ('image', models.ImageField(upload_to='ceilings', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('advantages', models.ManyToManyField(blank=True, to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u041f\u043e\u0442\u043e\u043b\u043e\u043a',
                'verbose_name_plural': '\u041f\u043e\u0442\u043e\u043b\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='CeilingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435', upload_to='ceilings/', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '500x320', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 500x320')),
                ('cropping_250x375', image_cropping.fields.ImageRatioField('image', '250x375', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430 250x375')),
                ('cropping_750x455', image_cropping.fields.ImageRatioField('image', '750x455', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='\u041e\u0431\u0440\u0435\u0437\u043a\u0430  750x455')),
                ('ceiling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ceilings.Ceiling', verbose_name='\u0412\u044b\u0431\u0440\u0430\u0442\u044c \u043f\u043e\u0442\u043e\u043b\u043e\u043a')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0438.', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='\u041c\u0435\u0442\u0430 title')),
                ('meta_description', models.CharField(blank=True, help_text='\u041d\u0443\u0436\u043d\u043e \u0434\u043b\u044f \u0421\u0415\u041e', max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('advantages', models.ManyToManyField(blank=True, to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0438\u0439 \u0444\u0438\u043b\u044c\u0442\u0440 \u0434\u043b\u044f \u0442\u0435\u043a\u0443\u0449\u0435\u0433\u043e', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='ceilings.Filter', verbose_name='\u0420\u043e\u0434\u0438\u0442\u0435\u043b\u044c\u0441\u043a\u0430\u044f \u0444\u0438\u043b\u044c\u0442\u0440')),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name': '\u0424\u0438\u043b\u044c\u0442\u0440',
                'verbose_name_plural': '\u0424\u0438\u043b\u044c\u0442\u0440\u044b',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='FilterAdvantages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceilings.Filter', verbose_name='\u0424\u0438\u043b\u044c\u0442\u0440 \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043f\u0440\u0438\u043d\u0430\u0434\u043b\u0435\u0436\u0438\u0442 \u043f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u043e')),
            ],
        ),
        migrations.CreateModel(
            name='FilterType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('slug', models.SlugField(help_text='\u0421\u0441\u044b\u043b\u043a\u0430 \u0444\u043e\u0440\u043c\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u0430\u0432\u0442\u043e\u043c\u0430\u0442\u0438\u0447\u0435\u0441\u043a\u0438 \u043f\u0440\u0438 \u0437\u0430\u043f\u043e\u043b\u043d\u0435\u043d\u0438\u0438.', unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='\u041c\u0435\u0442\u0430 title')),
                ('meta_description', models.CharField(blank=True, help_text='\u041d\u0443\u0436\u043d\u043e \u0434\u043b\u044f \u0421\u0415\u041e', max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='\u041c\u0435\u0442\u0430 \u043a\u043b\u044e\u0447\u0435\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u0438\u044f')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('advantages', models.ManyToManyField(blank=True, to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430')),
            ],
            options={
                'verbose_name': '\u0422\u0438\u043f \u0444\u0438\u043b\u044c\u0442\u0440\u0430 \u043f\u043e\u0442\u043e\u043b\u043a\u043e\u0432',
                'verbose_name_plural': '\u0422\u0438\u043f\u044b \u0444\u0438\u043b\u044c\u0442\u0440\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='filter',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ceilings.FilterType', verbose_name='\u0442\u0438\u043f \u0444\u0438\u043b\u044c\u0442\u0440\u0430'),
        ),
        migrations.AddField(
            model_name='ceiling',
            name='filter',
            field=models.ManyToManyField(blank=True, to='ceilings.Filter'),
        ),
    ]
