# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-08 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ceiling',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ceilings', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='ceiling',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\xb2'),
        ),
    ]
