# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 21:20
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0003_auto_20160514_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceiling',
            name='icon',
        ),
        migrations.AddField(
            model_name='ceiling',
            name='image',
            field=models.ImageField(default='', upload_to='ceilings', verbose_name='\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filter',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filtertype',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
