# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0006_auto_20160517_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceiling',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5, verbose_name='\u0426\u0435\u043d\u0430 \u0437\u0430 \u043c\xb2'),
            preserve_default=False,
        ),
    ]
