# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceilings', '0009_filteradvantages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filteradvantages',
            name='slug',
        ),
        migrations.AlterField(
            model_name='filteradvantages',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430'),
        ),
    ]
