# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20160521_1155'),
        ('ceilings', '0012_auto_20160519_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceiling',
            name='advantages',
            field=models.ManyToManyField(to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='filter',
            name='advantages',
            field=models.ManyToManyField(to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430'),
        ),
        migrations.AddField(
            model_name='filtertype',
            name='advantages',
            field=models.ManyToManyField(to='core.Advantages', verbose_name='\u041f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430'),
        ),
    ]
