# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20160219_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_teacher',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], default='teacher', max_length=200),
            preserve_default=False,
        ),
    ]
