# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160219_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('teacher', 'Учитель'), ('student', 'Ученик')], max_length=200, verbose_name='Выберите роль пользователя'),
        ),
    ]
