# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 11:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20160223_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442', 'verbose_name_plural': '\u0410\u043a\u043a\u0430\u0443\u043d\u0442\u044b'},
        ),
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u0430', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438 \u0417\u0430\u043a\u0430\u0437\u0447\u0438\u043a\u043e\u0432'},
        ),
        migrations.AlterModelOptions(
            name='performerprofile',
            options={'verbose_name': '\u041f\u0440\u043e\u0444\u0438\u043b\u044c \u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044f', 'verbose_name_plural': '\u041f\u0440\u043e\u0444\u0438\u043b\u0438 \u0418\u0441\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u0435\u0439'},
        ),
        migrations.AlterField(
            model_name='performerprofile',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
