# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20160410_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='performerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=b'accounts', verbose_name='\u0430\u0432\u0430\u0442\u0430\u0440'),
        ),
    ]
